# Generated by Django 3.2.13 on 2022-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='disponibility',
            field=models.CharField(default=1, max_length=3, verbose_name='Disponible'),
            preserve_default=False,
        ),
    ]
