# Generated by Django 3.2.13 on 2022-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_produit_disponibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='disponibility',
            field=models.CharField(max_length=5, verbose_name='Disponible'),
        ),
    ]
