# Generated by Django 3.2.13 on 2022-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220608_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_order', models.CharField(max_length=8, verbose_name='num_commande')),
                ('num_cli', models.CharField(max_length=8, verbose_name='num_cli')),
                ('name_cli', models.CharField(max_length=50, verbose_name='nom_cli')),
                ('total', models.CharField(max_length=5, verbose_name='total')),
            ],
        ),
    ]
