# Generated by Django 3.2.13 on 2022-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.CharField(max_length=7, verbose_name='total'),
        ),
    ]
